spring:
  jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: git-api-test
  main:
    allow-bean-definition-overriding: true

github:
  url: https://api.github.com

server:
  port: 8080
  servlet:
    context-path: /api/space/vc
management:
  server:
    port: 8080
